[package]
name = "p0033"
version = "0.1.0"
authors = ["Scott Bailey <Scott@BaileyBuilt.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fraction = "0.8.0"
#num-bigint = "0.4"
#sb = { path = "../sb" }
