[package]
name = "p0024"
version = "0.1.0"
authors = ["Scott Bailey <Scott@BaileyBuilt.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
#sb = { path = "../sb" }
